### ISSUE TITLE
Keep reading 885 from MX28 and MX64 with protocol 2

### ISSUE THREAD

**Issue by aidengk-iris** [pollen-robotics/rustypot#59]
Dear all,

I was trying to read the current positions from 7 MX series motors (6 MX28 and 1 MX64 daisy chained).
I received only the value 885 regardless if I use `mx::read_present_position` or `mx::sync_read_present_position`. Even if I rotate the motors a lot, I only received 885. 

I could read all kind of information from the motors via DynamixelWizard2 and I saw motors' positions change as I move them. Therefore, I suppose something is wrong with my implementation. The code I used to read motors positions is as follows:

```
use rustypot::{device::mx::{self, sync_read_present_position}, DynamixelSerialIO};
use std::{thread::sleep, time::Duration};

fn main() {
    let mut serial_port = serialport::new("COM12", 2_000_000)
        .timeout(Duration::from_millis(20))
        .open()
        .expect("Failed to open port");

    let io_v2 = DynamixelSerialIO::v2();

    loop {
        // let current_positions = sync_read_present_position(&io_v2,  serial_port.as_mut(), &[0,1,2,3,4,5,6]).expect("Error reading motor positions!");
        for motor_id in 0..7{
            let current_position = mx::read_present_position(&io_v2, serial_port.as_mut(), motor_id).expect("error reading pos");
            println!("id: {}, position: {}", motor_id, current_position);
        }
        // println!("{:?}", current_positions);
        sleep(Duration::from_millis(10));
    }
}
```

I appreciate any insight from you. Thank you very much.

**Comment by SteveNguyen** [comment]
Hi, 
I see you are using the Dynamixel protocol v2. Did you upgrade the firmware to be in protocol v2? 
Otherwise you should try with v1.
If you upgraded to v2, I am afraid we have to write a specific device like mx_v2.rs with different registers as they are not compatible:
In v1: https://emanual.robotis.com/docs/en/dxl/mx/mx-28/#control-table-description
in v2: https://emanual.robotis.com/docs/en/dxl/mx/mx-28-2/#control-table-data-address
Feel free to make a PR.

**Comment by aidengk-iris** [comment]
Thank you @SteveNguyen , yes the motor firmware was updated to support protocol 2. And I confirm the wrong register map is indeed the issue with protocol v2. 

I'll close the issue.
